export const TOPIC_BANK = {
  EARLY: [
    "Analyzing baseline assessment data to identify student learning gaps",
    "Establishing team norms and collaborative protocols for the academic year",
    "Mapping out key learning objectives for the first term curriculum",
    "Developing common formative assessments for introductory units",
    "Identifying students for early Tier 2 interventions based on initial data",
    "Aligning classroom routines to maximize instructional time",
    "Sharing best practices for student engagement during the first month",
    "Setting professional growth goals and identifying areas for peer observation",
    "Discussing how to communicate learning expectations clearly to students",
    "Reviewing prerequisite skills needed for the upcoming units of study",
    "Sharing strategies for building a positive classroom learning culture",
    "Identifying essential standards that all students must master this term",
    "Discussing how to use student interest surveys to plan lessons",
    "Planning for the first cycle of peer observations and feedback",
    "Reviewing school-wide literacy and numeracy goals for the year",
    "Discussing how to simplify learning objectives for student understanding",
    "Sharing ways to check for prerequisite knowledge before a new unit",
    "Reviewing the most common learning gaps from the previous grade level",
    "Planning how to use classroom space to support small group learning",
    "Discussing how to set up a 'help desk' or resource area for students",
    "Sharing ideas for quick morning check-ins that focus on learning readiness",
    "Reviewing the school's literacy goals and how they apply to every subject",
    "Discussing how to teach students to track their own learning progress",
    "Sharing ways to make learning targets visible and meaningful to students",
    "Planning for the first week of intensive reading or math support",
    "Discussing how to introduce new vocabulary in a way that sticks",
    "Sharing ideas for building student confidence in difficult subjects",
    "Reviewing the data from the most recent standardized tests",
    "Discussing how to organize student folders for easy progress tracking",
    "Sharing strategies for teaching students how to ask for help effectively",
    "Planning how to involve parents in supporting specific learning goals",
    "Discussing the best way to group students for the first collaborative project",
    "Sharing ideas for 'entrance tickets' to gauge student readiness",
    "Reviewing the essential questions for the first major unit of study",
    "Discussing how to handle early finishers with meaningful extension tasks",
    "Sharing ways to make homework more focused on practice and less on new learning",
    "Planning how to use peer mentors in the classroom early on",
    "Discussing how to teach students to use rubrics for self-assessment",
    "Sharing ideas for a 'word wall' that students actually use",
    "Reviewing the schedule to ensure maximum time for core subjects",
    "Discussing how to simplify complex instructions for younger learners",
    "Sharing ways to use visual aids to support English language learners",
    "Planning for the first parent-teacher meeting focused on learning goals",
    "Discussing how to identify 'hidden' learning barriers in the first month",
    "Sharing ideas for building a 'growth mindset' through specific feedback",
    "Reviewing the curriculum for potential 'bottlenecks' in student understanding",
    "Discussing how to use digital tools for quick baseline assessments",
    "Sharing ways to make math manipulatives accessible and organized",
    "Planning for a 'literacy rich' environment in every classroom",
    "Discussing how to teach students to take simple, effective notes",
    "Sharing ideas for 'learning stations' that require minimal setup",
    "Reviewing the most important vocabulary for the first term",
    "Discussing how to handle different reading levels in a single class",
    "Sharing ways to encourage students to explain their thinking out loud",
    "Planning how to use 'think-pair-share' to increase participation",
    "Discussing how to set up a classroom library that matches student levels",
    "Sharing ideas for quick 'check for understanding' hand signals",
    "Reviewing the school's numeracy strategy for the upcoming term",
    "Discussing how to make science experiments safe and learning-focused",
    "Sharing ways to use storytelling to introduce new history topics",
    "Planning for a 'math talk' routine to build number sense",
    "Discussing how to use anchor charts to support independent work",
    "Sharing ideas for 'brain breaks' that reinforce learning concepts",
    "Reviewing the first unit's assessment to ensure it matches the standards",
    "Discussing how to build a community of learners who support each other",
    "Math: Assessing student understanding of place value up to 1,000",
    "English: Identifying students struggling with basic phonics and decoding",
    "Science: Setting up a classroom 'science corner' for daily observations",
    "Social Studies: Discussing how to teach the concept of 'community' to young learners",
    "Computing: Reviewing student knowledge of basic computer hardware and safety",
    "Math: Sharing strategies for teaching addition and subtraction with regrouping",
    "English: Developing a routine for daily independent reading in the classroom",
    "Science: Planning the first hands-on experiment focused on the five senses",
    "Social Studies: Identifying key historical figures to introduce in the first month",
    "Computing: Discussing how to teach digital citizenship and online kindness",
    "Math: Reviewing student performance on basic multiplication and division facts",
    "English: Sharing ideas for teaching students how to write a simple paragraph",
    "Science: Discussing how to introduce the scientific method through simple play",
    "Social Studies: Planning a local 'geography walk' around the school grounds",
    "Computing: Sharing tips for helping students remember their login details",
    "Math: Identifying common errors in student understanding of simple fractions",
    "English: Discussing how to use picture books to build early comprehension skills",
    "Science: Reviewing the safety protocols for the first term's science lab",
    "Social Studies: Sharing ways to teach students about different family structures",
    "Computing: Planning the first lesson on basic word processing and typing",
    "Math: Discussing how to use math manipulatives to teach number bonds",
    "English: Sharing strategies for teaching high-frequency 'sight words' effectively",
    "Science: Identifying local plants and animals for a biology observation unit",
    "Social Studies: Reviewing how to teach the concept of 'past and present'",
    "Computing: Discussing the importance of 'unplugged' coding activities for beginners",
    "Math: Sharing ideas for a 'math wall' focused on early number patterns",
    "English: Planning a 'poetry corner' to encourage creative writing early on",
    "Science: Discussing how to teach the properties of water through simple experiments",
    "Social Studies: Sharing ways to introduce basic map skills and cardinal directions",
    "Computing: Reviewing the school's policy on student use of tablets and laptops",
    "Math: Identifying students who need extra support with basic measurement",
    "English: Discussing how to teach students to listen and respond during discussions",
    "Science: Planning a 'weather station' to track daily changes in the first term",
    "Social Studies: Sharing ideas for teaching students about national symbols and flags",
    "Computing: Discussing how to introduce the concept of 'algorithms' through daily routines",
    "Math: Reviewing student understanding of 2D and 3D shapes in the first month",
    "English: Sharing ways to use 'story maps' to help students plan their writing",
    "Science: Discussing how to teach the life cycle of a plant using real seeds",
    "Social Studies: Planning a 'classroom constitution' to teach about rules and laws",
    "Computing: Sharing tips for teaching students how to use a mouse or trackpad",
    "Math: Identifying common misconceptions in student understanding of time",
    "English: Discussing how to teach students to identify the 'main idea' of a story",
    "Science: Reviewing the basic needs of living things with simple examples",
    "Social Studies: Sharing ways to teach students about their local neighborhood",
    "Computing: Planning the first lesson on how to search for information safely online",
    "Math: Discussing how to use 'number lines' to support early calculation",
    "English: Sharing ideas for 'spelling' games that focus on common patterns",
    "Science: Reviewing how to teach the concept of 'push and pull' forces",
    "Social Studies: Discussing how to introduce the concept of 'wants and needs'",
    "Computing: Sharing ways to use educational apps to support early literacy"
  ],
  MID: [
    "Evaluating mid-term assessment results to adjust instructional pacing",
    "Analyzing student work samples to identify common misconceptions",
    "Developing differentiated lesson plans for diverse learning needs",
    "Implementing peer-feedback strategies to improve student writing",
    "Reviewing the effectiveness of current intervention strategies for at-risk students",
    "Integrating technology tools to enhance collaborative learning",
    "Discussing strategies for improving student attendance and participation",
    "Aligning cross-curricular projects to reinforce core learning standards",
    "Sharing quick formative assessment techniques like exit tickets",
    "Analyzing student data to regroup students for targeted instruction",
    "Discussing how to provide high-quality feedback that drives student growth",
    "Sharing strategies for teaching complex concepts in simple ways",
    "Reviewing student progress on individual learning plans (ILPs)",
    "Discussing how to manage classroom behavior to support learning",
    "Sharing tips for effective parent-teacher communication about student progress",
    "Analyzing the results of the first major unit test to plan re-teaching",
    "Sharing ways to differentiate a single lesson for three different levels",
    "Discussing how to use 'error analysis' to help students learn from mistakes",
    "Sharing ideas for 'choice boards' that allow students to show what they know",
    "Reviewing the progress of students in the Tier 2 intervention groups",
    "Discussing how to provide faster feedback on student writing assignments",
    "Sharing ways to use 'scaffolding' to help students reach higher standards",
    "Planning how to adjust the pacing guide if students are falling behind",
    "Discussing how to use 'guided reading' groups effectively in a busy class",
    "Sharing ideas for 'math games' that focus on specific skill gaps",
    "Reviewing student work to find the 'best' examples of a specific skill",
    "Discussing how to help students who are struggling with multi-step problems",
    "Sharing ways to use 'peer editing' to improve the quality of student work",
    "Planning for a 'mid-term review' that is engaging and effective",
    "Discussing how to use 'data walls' (privately) to track group progress",
    "Sharing ideas for 'flipped classroom' elements to save class time",
    "Reviewing the use of 'manipulatives' in upper primary math lessons",
    "Discussing how to encourage 'productive struggle' in problem-solving",
    "Sharing ways to use 'questioning techniques' to deepen student thinking",
    "Planning how to support students with special educational needs (SEN) mid-term",
    "Discussing how to use 'formative data' to change tomorrow's lesson plan",
    "Sharing ideas for 'vocabulary building' games that students enjoy",
    "Reviewing the effectiveness of current 'homework' policies on learning",
    "Discussing how to help students transition between different subjects",
    "Sharing ways to use 'rubrics' to give more specific feedback",
    "Planning for a 'data chat' with individual students about their progress",
    "Discussing how to use 'visual organizers' to help students plan writing",
    "Sharing ideas for 'science journals' that track student observations",
    "Reviewing the alignment between classroom activities and the mid-term test",
    "Discussing how to handle 'learning plateaus' in reading or math",
    "Sharing ways to use 'technology' to provide instant feedback to students",
    "Planning how to involve 'teaching assistants' more effectively in lessons",
    "Discussing how to teach 'critical thinking' through simple debates",
    "Sharing ideas for 'project-based learning' that fits into a tight schedule",
    "Reviewing the most common 'spelling' or 'grammar' errors in student work",
    "Discussing how to help students 'visualize' math problems",
    "Sharing ways to use 'music' or 'rhythm' to memorize key facts",
    "Planning for a 'peer observation' focused on student engagement",
    "Discussing how to use 'exit tickets' to group students for the next day",
    "Sharing ideas for 'interactive notebooks' that students find useful",
    "Reviewing the 'reading aloud' routine to ensure it builds comprehension",
    "Discussing how to help students 'connect' new learning to old learning",
    "Sharing ways to use 'real-world examples' to make lessons more relevant",
    "Planning how to support 'advanced learners' who finish work early",
    "Discussing how to use 'wait time' to encourage more student responses",
    "Sharing ideas for 'collaborative posters' to summarize a unit",
    "Reviewing the 'grading' process to ensure it is fair and consistent",
    "Discussing how to help students 'summarize' what they learned each day",
    "Sharing ways to use 'movement' to teach abstract concepts",
    "Planning for a 'mid-term celebration' of student learning growth",
    "Math: Analyzing student errors in multi-digit multiplication problems",
    "English: Developing strategies to help students write more descriptive sentences",
    "Science: Reviewing student understanding of the water cycle through diagrams",
    "Social Studies: Discussing how to teach the impact of historical events on today",
    "Computing: Sharing ideas for teaching basic block-based coding (like Scratch)",
    "Math: Identifying common misconceptions in student understanding of decimals",
    "English: Reviewing student progress in identifying character traits in literature",
    "Science: Planning an experiment to test the properties of different materials",
    "Social Studies: Sharing ways to teach students about cultural diversity in our region",
    "Computing: Discussing how to teach students to create simple digital presentations",
    "Math: Sharing strategies for teaching students how to solve complex word problems",
    "English: Reviewing student work on persuasive writing and identifying areas for growth",
    "Science: Discussing how to teach the concept of 'ecosystems' through local examples",
    "Social Studies: Planning a project on how local government works for the community",
    "Computing: Sharing tips for teaching students about internet safety and privacy",
    "Math: Identifying students struggling with the concept of area and perimeter",
    "English: Discussing how to teach students to use 'context clues' to find word meanings",
    "Science: Reviewing student understanding of simple machines and how they work",
    "Social Studies: Sharing ways to teach students about the history of their own town",
    "Computing: Planning a lesson on how to use digital spreadsheets for simple data",
    "Math: Sharing ideas for 'math centers' focused on equivalent fractions",
    "English: Reviewing student progress in using correct punctuation in longer stories",
    "Science: Discussing how to teach the human body systems in a simple, clear way",
    "Social Studies: Sharing ways to teach students about different types of maps",
    "Computing: Discussing how to teach students to troubleshoot simple tech problems",
    "Math: Identifying common errors in student understanding of long division",
    "English: Sharing strategies for teaching students how to write a formal letter",
    "Science: Planning an experiment on how light travels and reflects",
    "Social Studies: Reviewing how to teach the concept of 'supply and demand'",
    "Computing: Sharing ideas for 'digital storytelling' projects using simple tools",
    "Math: Discussing how to help students understand the relationship between fractions and decimals",
    "English: Reviewing student work on 'compare and contrast' essays",
    "Science: Sharing ways to teach students about the states of matter (solid, liquid, gas)",
    "Social Studies: Planning a lesson on the importance of landmarks in our country",
    "Computing: Discussing how to teach students to evaluate the reliability of websites",
    "Math: Identifying students who need extra support with geometry and angles",
    "English: Sharing ideas for teaching students how to use 'dialogue' in their writing",
    "Science: Reviewing student understanding of the solar system and planets",
    "Social Studies: Sharing ways to teach students about the rights and responsibilities of citizens",
    "Computing: Planning a project where students create a simple website or blog",
    "Math: Discussing how to use 'probability' games to teach basic statistics",
    "English: Reviewing student progress in identifying 'cause and effect' in reading",
    "Science: Sharing strategies for teaching students about sound and vibrations",
    "Social Studies: Discussing how to teach the concept of 'migration' and its impact",
    "Computing: Sharing tips for teaching students how to use digital cameras for projects",
    "Math: Identifying common misconceptions in student understanding of percentages",
    "English: Reviewing student work on 'biographies' and identifying key research skills",
    "Science: Planning an experiment on how plants respond to different environments",
    "Social Studies: Sharing ways to teach students about the different branches of government",
    "Computing: Discussing how to teach students to use 'email' professionally and safely"
  ],
  END: [
    "Reflecting on end-of-term data to measure growth against annual targets",
    "Preparing transition reports and recommendations for the upcoming term",
    "Reviewing the impact of PLC collaborative efforts on student achievement",
    "Developing summative assessment rubrics for final projects",
    "Identifying successful instructional strategies to be scaled in the next term",
    "Analyzing student feedback to improve classroom environment and instruction",
    "Planning for end-of-year standardized testing and review sessions",
    "Reflecting on team successes and identifying areas for PLC improvement",
    "Discussing how to support students who did not meet learning targets",
    "Sharing one instructional strategy that significantly improved student learning",
    "Reviewing the alignment between our assessments and our learning goals",
    "Discussing how to maintain student learning momentum during breaks",
    "Planning the curriculum map for the next academic term",
    "Reflecting on the professional growth goals set at the start of the year",
    "Identifying professional development needs for the next term",
    "Analyzing final assessment data to see which standards were mastered",
    "Sharing the 'most successful' lesson of the term and why it worked",
    "Discussing how to prepare students for the transition to the next grade",
    "Reviewing the 'learning growth' of the most struggling students",
    "Planning how to use the final week for 'enrichment' and 'review'",
    "Discussing how to write 'meaningful' comments on end-of-term reports",
    "Sharing ideas for 'student portfolios' that show progress over time",
    "Reviewing the 'PLC goals' set at the start and whether they were met",
    "Discussing how to 'scale up' a successful intervention to more students",
    "Sharing ways to involve students in 'reflecting' on their own growth",
    "Planning for 'standardized test' preparation without causing stress",
    "Discussing how to handle 'summer learning loss' with simple home ideas",
    "Sharing ideas for 'end-of-term projects' that synthesize all learning",
    "Reviewing the 'curriculum map' to see what needs to be adjusted next year",
    "Discussing how to improve 'team collaboration' for the next term",
    "Sharing the 'most helpful' teaching resource found this term",
    "Planning for the 'first unit' of the next term based on current data",
    "Discussing how to 'celebrate' student achievement in a professional way",
    "Sharing ways to use 'student feedback' to improve teaching practice",
    "Reviewing the 'professional development' needs identified this term",
    "Discussing how to 'hand over' student data to the next teacher",
    "Sharing ideas for 'final presentations' that build student confidence",
    "Planning how to 'recharge' and 'reflect' during the school break",
    "Discussing the 'biggest challenge' faced this term and how it was solved",
    "Sharing ways to make 'end-of-year testing' more manageable for students",
    "Reviewing the 'impact' of specific technology tools on learning",
    "Discussing how to 'simplify' the reporting process for teachers",
    "Sharing ideas for 'community showcases' of student learning",
    "Planning for 'new student' orientations for the next academic year",
    "Discussing how to 'archive' student work and data effectively",
    "Sharing ways to 'mentor' new teachers joining the PLC next term",
    "Reviewing the 'budget' for learning resources for the next term",
    "Discussing how to 'integrate' more social-emotional learning next year",
    "Sharing ideas for 'outdoor learning' activities for the final weeks",
    "Planning for a 'PLC retreat' or 'reflection day' at the end of term",
    "Discussing how to 'standardize' grading across the whole department",
    "Sharing ways to 'improve' parent engagement for the next term",
    "Reviewing the 'safety' and 'accessibility' of learning materials",
    "Discussing how to 'update' the classroom environment for a fresh start",
    "Sharing ideas for 'student-led' conferences at the end of the term",
    "Planning for 'cross-grade' collaboration to ensure smooth transitions",
    "Discussing how to 'use' the data from final exams to plan for next year",
    "Sharing ways to 'encourage' students to keep reading over the break",
    "Reviewing the 'mission and vision' of the PLC for the next year",
    "Discussing how to 'reduce' teacher burnout through better systems",
    "Sharing ideas for 'digital portfolios' that follow students through grades",
    "Planning for 'curriculum innovation' in the upcoming academic year",
    "Discussing how to 'better support' students with diverse backgrounds",
    "Sharing the 'best' piece of student work produced this whole term",
    "Reflecting on our 'identity' as a PLC and how we've grown together",
    "Math: Reviewing end-of-year data on student mastery of all four operations",
    "English: Analyzing final writing portfolios to measure growth in descriptive language",
    "Science: Planning a final 'science fair' where students present their own experiments",
    "Social Studies: Discussing how to summarize the major historical themes learned this year",
    "Computing: Reviewing student final projects in coding or digital design",
    "Math: Identifying key math skills that students will need for the next grade level",
    "English: Sharing ideas for an end-of-year 'book talk' or literature circle",
    "Science: Reviewing student understanding of environmental conservation and recycling",
    "Social Studies: Planning a 'global citizenship' project focused on world issues",
    "Computing: Discussing how to help students 'clean up' and archive their digital work",
    "Math: Analyzing student performance on multi-step word problems in final tests",
    "English: Reviewing student progress in public speaking and presentation skills",
    "Science: Sharing ways to teach students about the impact of technology on science",
    "Social Studies: Discussing how to teach the concept of 'interdependence' in the world",
    "Computing: Planning a final lesson on the future of technology and AI",
    "Math: Identifying students who need a 'summer bridge' program for math skills",
    "English: Sharing ideas for a 'summer reading list' that matches student interests",
    "Science: Reviewing student understanding of the human impact on the planet",
    "Social Studies: Planning a 'history timeline' project that covers the whole year",
    "Computing: Discussing how to teach students to protect their 'digital footprint'",
    "Math: Analyzing student data on measurement and data analysis skills",
    "English: Reviewing final essay work to identify common areas for next year's focus",
    "Science: Sharing strategies for teaching students about renewable energy sources",
    "Social Studies: Discussing how to teach the concept of 'justice' and 'equality'",
    "Computing: Planning a 'coding challenge' for the final week of school",
    "Math: Identifying the most 'essential' math standards for transition reports",
    "English: Sharing ideas for a 'class newspaper' that summarizes the year's events",
    "Science: Reviewing student understanding of the life cycles of different animals",
    "Social Studies: Planning a 'cultural exchange' day to celebrate diversity",
    "Computing: Discussing how to teach students to use 'search engines' more effectively",
    "Math: Analyzing student performance on geometry and spatial reasoning",
    "English: Reviewing student progress in using 'figurative language' in writing",
    "Science: Sharing ways to teach students about the importance of biodiversity",
    "Social Studies: Discussing how to teach the concept of 'global trade' simply",
    "Computing: Planning a project where students 'teach' a tech skill to a peer",
    "Math: Identifying students who have shown the most growth in number sense",
    "English: Sharing ideas for 'creative writing' prompts for the final weeks",
    "Science: Reviewing student understanding of the rock cycle and earth's layers",
    "Social Studies: Planning a 'mock election' to teach about the democratic process",
    "Computing: Discussing how to help students identify 'fake news' online",
    "Math: Analyzing student data on time and money management skills",
    "English: Reviewing student progress in 'reading for information' and research",
    "Science: Sharing strategies for teaching students about electricity and circuits",
    "Social Studies: Discussing how to teach the concept of 'sustainability'",
    "Computing: Planning a final 'digital art' project to celebrate the year",
    "Math: Identifying key 'mental math' strategies to reinforce before the break",
    "English: Sharing ideas for a 'poetry slam' to showcase student voices",
    "Science: Reviewing student understanding of the classification of living things",
    "Social Studies: Planning a 'local history' showcase for parents and community",
    "Computing: Discussing how to 'hand over' digital progress reports to next year's teachers"
  ]
};

export const DEFAULT_STAFF = [
  { id: '1', name: 'John Doe', signature: '' },
  { id: '2', name: 'Jane Smith', signature: '' },
  { id: '3', name: 'Robert Brown', signature: '' }
];
